on:
  push:
    branches:
      - main
      - "release/**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v6.0.2

      - name: run this for running test
        run: echo "this is test"
